import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";

// تعریف فونت Rajdhani از گوگل
const rajdhani = Rajdhani({
  subsets: ["latin"], // زیرمجموعه زبان‌ها، اگر فقط به لاتین نیاز دارید
  weight: ["400", "700"], // فقط وزن‌های مورد نیاز
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rajdhani.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
